[book]
title = "Basic JavaScript, HTML and CSS: How to build a To Do List from scratch"
authors = ["LazyYuuki"]
language = "en"
multilingual = false
src = "src"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
additional-css = ["modified-mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
